version: '3.1'
networks:
  todonetwork:
    driver: bridge

services:
  database:
    image: postgres:9-alpine
    restart: always
    networks:
      - todonetwork
    container_name: dbserver
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - tododb_data:/var/lib/postgresql/data
  todoapi:
    build:
      context: .
    container_name: todoapi
    networks:
      - todonetwork
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
volumes:
  tododb_data:
